modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="ironblood"
version="0.0.0"
displayName="ironblood"
displayURL="https://github.com/greathive/ironblood"
credits="greathive"
authors="greathive"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.ironblood]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration